name: Android APK

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      # Usa Gradle senza wrapper: il build-action installerà Gradle 8.7
      - name: Gradle assembleDebug
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.7"
          arguments: assembleDebug -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
